#!/usr/bin/env python3

import rospy
from std_msgs.msg import Int32

def run():
    rospy.init_node('drive_publisher')

    pub = rospy.Publisher('drive', Int32, queue_size=10)
    
    while not rospy.is_shutdown():
        cmd = input("Press enter to change direction")
        pub.publish()

if __name__ == "__main__":
    try:
        run()
    except KeyboardInterrupt:
        pass